# Use a lightweight Nginx image as the base
FROM nginx:alpine

WORKDIR /frontend
# Copy your static files into the Nginx default directory
COPY . .

# Expose port 80 (the default Nginx port)
EXPOSE 80

# Nginx configuration (optional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Nginx starts automatically by default, so no CMD is needed