# Use Python 3.10 base image
FROM python:3.10-slim

# Set working directory
WORKDIR /backend

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY . .

# Expose port for FastAPI
EXPOSE 8000

# Command to run the application
CMD ["sh", "-c", "python populate_database.py && uvicorn app:app --host 0.0.0.0 --port 8000"]
